sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: nightly

before_script: composer install

script: composer test

after_script: vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: 4957dbed55094d836b153e66f83b3fd50769d5d0423d9206f5598fb78741c907

notifications:
  - email: false
