language: php

matrix:
  include:
  - php: 5.3
    dist: precise
  - php: 5.4
  - php: 5.5
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: nightly
  - php: hhvm
  fast_finish: true
  allow_failures:
  - php: nightly
  - php: 7.2
  - php: hhvm

before_script: composer install

script: composer test

after_script: vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: 4957dbed55094d836b153e66f83b3fd50769d5d0423d9206f5598fb78741c907

notifications:
  - email: false
